/* DO NOT EDIT THIS FILE - it is machine generated */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <jni.h>
#include <android/log.h>
/* Header for class com_hxsmart_imateinterface_pbocsdk_PbocApi */

#include "unsigned.h"
#include "EmvProc.h"
#include "RemoteFunctions.h"
#include "iMateExt.h"

static JNIEnv *sg_env;
static jobject sg_this;

static jmethodID sendReceiveCallBack;

static void vSetIntegerValue(JNIEnv *env, jobject obj, int value);
static void vSetBooleanValue(JNIEnv *env, jobject obj, int value);
static void vSetFieldByteArray(JNIEnv *env, jobject obj, const char *szParamName, jbyteArray buffer, int len);
static void vSetFieldString(JNIEnv *env, jobject obj, const char *szParamName, const char *szValue);
static int iGetFieldString(JNIEnv *env, jobject obj, const char *szParamName, char *szValue);
static void vSetFieldInt(JNIEnv *env, jobject obj, const char *szParamName, int iValue);
static jint iGetFieldInt(JNIEnv *env, jobject obj, const char *szParamName);

/*
 * Class:     com_hxsmart_imateinterface_pbocsdk_PbocApi
 * Method:    iHxEmvInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_hxsmart_imateinterface_pbocsdk_PbocApi_iHxEmvInitNative
  (JNIEnv *env, jobject thiz)
{
	sg_env = env;
	sg_this = thiz;

    jclass thisclass = (*env)->GetObjectClass(env, thiz);
    sendReceiveCallBack = (*env)->GetMethodID(env, thisclass, "sendReceiveCallBack", "([BI[BI)I");
    if (sendReceiveCallBack == 0)
    	return HXEMV_CORE;

    return iHxEmvInit(iIMateTestCard,iIMateResetCard,iIMateExchangeApdu,iIMateCloseCard);
}

/*
 * Class:     com_hxsmart_imateinterface_pbocsdk_PbocApi
 * Method:    iHxEmvInfo
 * Signature: (Lcom/hxsmart/imateinterface/pbocsdk/HxEmvInfo;)I
 */
JNIEXPORT jint JNICALL Java_com_hxsmart_imateinterface_pbocsdk_PbocApi_iHxEmvInfo
  (JNIEnv *env, jobject thiz, jobject emvInfo)
{
	sg_env = env;
	sg_this = thiz;

	if (emvInfo == NULL)
		return HXEMV_PARA;

	uchar szCoreName[40+1];
	uchar szCoreDesc[60+1];
	uchar szCoreVer[10+1];
	uchar szReleaseDate[10+1];
	uchar szCustomerDesc[100+1];
	memset(szCustomerDesc, 0, sizeof(szCustomerDesc));

	int iRet = iHxEmvInfo(szCoreName, szCoreDesc, szCoreVer, szReleaseDate, szCustomerDesc);
	if (iRet != HXEMV_OK)
		return iRet;

	vSetFieldString(env, emvInfo, "coreName", szCoreName);
	vSetFieldString(env, emvInfo, "coreDesc", szCoreDesc);
	vSetFieldString(env, emvInfo, "coreVer", szCoreVer);
	vSetFieldString(env, emvInfo, "releaseDate", szReleaseDate);

	return HXEMV_OK;
}

/*
 * Class:     com_hxsmart_imateinterface_pbocsdk_PbocApi
 * Method:    iHxEmvSetParam
 * Signature: (Lcom/hxsmart/imateinterface/pbocsdk/HxTermParam;)I
 */
JNIEXPORT jint JNICALL Java_com_hxsmart_imateinterface_pbocsdk_PbocApi_iHxEmvSetParam
  (JNIEnv *env, jobject thiz, jobject termParam)
{
	sg_env = env;
	sg_this = thiz;

	if (termParam == NULL)
		return HXEMV_PARA;

	stHxTermParam TermParam;
	memset(&TermParam, 0, sizeof(stHxTermParam));

	TermParam.ucTermType = iGetFieldInt(env, termParam, "termType");
	char szBuffer[300];
	if (iGetFieldString(env, termParam, "termCapability", szBuffer))
		vTwoOne(szBuffer, 6, TermParam.sTermCapability);
	if (iGetFieldString(env, termParam, "additionalTermCapability", szBuffer))
		vTwoOne(szBuffer, 10, TermParam.sAdditionalTermCapability);
	if (iGetFieldString(env, termParam, "merchantId", szBuffer))
		strncpy(TermParam.szMerchantId, szBuffer, 15);
	if (iGetFieldString(env, termParam, "termId", szBuffer))
		strncpy(TermParam.szTermId, szBuffer, 8);
	if (iGetFieldString(env, termParam, "merchantNameLocation", szBuffer))
		strncpy(TermParam.szMerchantNameLocation, szBuffer, 254);
	TermParam.uiTermCountryCode = iGetFieldInt(env, termParam, "termCountryCode");
	if (iGetFieldString(env, termParam, "acquirerId", szBuffer))
		strncpy(TermParam.szAcquirerId, szBuffer, 11);

	TermParam.iMerchantCategoryCode = -1;
	TermParam.ucPinBypassBehavior = 0;
	TermParam.ucAppConfirmSupport = 0;

	if (iGetFieldString(env, termParam, "termAppVer", szBuffer))
		vTwoOne(szBuffer, 4, TermParam.AidCommonPara.sTermAppVer);

	TermParam.AidCommonPara.ulFloorLimit = iGetFieldInt(env, termParam, "floorLimit");
	TermParam.AidCommonPara.iMaxTargetPercentage = iGetFieldInt(env, termParam, "maxTargetPercentage");
	TermParam.AidCommonPara.iTargetPercentage = iGetFieldInt(env, termParam, "targetPercentage");
	TermParam.AidCommonPara.ulThresholdValue = iGetFieldInt(env, termParam, "thresholdValue");
	TermParam.AidCommonPara.ucECashSupport = (uchar)iGetFieldInt(env, termParam, "ecashSupport");
	if (iGetFieldString(env, termParam, "termECashTransLimit", szBuffer))
		strncpy(TermParam.AidCommonPara.szTermECashTransLimit, szBuffer, 12);

	if (iGetFieldString(env, termParam, "tacDefault", szBuffer) == 10) {
		TermParam.AidCommonPara.ucTacDefaultExistFlag = 1;
		vTwoOne(szBuffer, 10, TermParam.AidCommonPara.sTacDefault);
	}
	if (iGetFieldString(env, termParam, "tacDenial", szBuffer) == 10) {
		TermParam.AidCommonPara.ucTacDenialExistFlag = 1;
		vTwoOne(szBuffer, 10, TermParam.AidCommonPara.sTacDenial);
	}
	if (iGetFieldString(env, termParam, "tacOnline", szBuffer) == 10) {
		TermParam.AidCommonPara.ucTacOnlineExistFlag = 1;
		vTwoOne(szBuffer, 10, TermParam.AidCommonPara.sTacOnline);
	}
	TermParam.AidCommonPara.iDefaultDDOLLen = -1;
	TermParam.AidCommonPara.iDefaultTDOLLen = -1;

	return iHxEmvSetParam(&TermParam);
}

/*
 * Class:     com_hxsmart_imateinterface_pbocsdk_PbocApi
 * Method:    iHxEmvLoadAid
 * Signature: ([Lcom/hxsmart/imateinterface/pbocsdk/HxTermAid;)I
 */
JNIEXPORT jint JNICALL Java_com_hxsmart_imateinterface_pbocsdk_PbocApi_iHxEmvLoadAid
  (JNIEnv *env, jobject thiz, jobjectArray termAids)
{
	sg_env = env;
	sg_this = thiz;

	if( termAids == NULL)
		return HXEMV_PARA;

	int iHxTermAidNum = (*env)->GetArrayLength(env, termAids);
	int i;

	if (iHxTermAidNum == 0)
		return HXEMV_PARA;

	stHxTermAid TermAid[iHxTermAidNum];
	memset(TermAid, 0, sizeof(stHxTermAid) * iHxTermAidNum);

	for (i = 0; i< iHxTermAidNum; i++) {
		jobject obj = (*env)->GetObjectArrayElement(env, termAids,i);

		char szBuffer[60];
		int len;

		memset(szBuffer, 0, sizeof(szBuffer));
		len = iGetFieldString(env, obj, "aid", szBuffer);
		if (len <= 16)
			vTwoOne(szBuffer, len, TermAid[i].sAid);
		TermAid[i].ucAidLen = len / 2;
		TermAid[i].ucASI = iGetFieldInt(env, obj, "ASI");
		TermAid[i].cOnlinePinSupport = iGetFieldInt(env, obj, "OnlinePinSupport");

		memcpy(TermAid[i].sTermAppVer, "\xff\xff", 2);
		TermAid[i].ulFloorLimit = 0xFFFFFFFF;
		TermAid[i].iMaxTargetPercentage = -1;
		TermAid[i].iTargetPercentage = -1;
		TermAid[i].ulThresholdValue = 0xFFFFFFFF;
		TermAid[i].ucECashSupport = 0xff;
		strcpy(TermAid[i].szTermECashTransLimit, "");
		TermAid[i].ucTacDefaultExistFlag = 0;
		TermAid[i].ucTacDenialExistFlag = 0;
		TermAid[i].ucTacOnlineExistFlag = 0;

		TermAid[i].iDefaultDDOLLen = -1;
		TermAid[i].iDefaultTDOLLen = -1;
	}
	return iHxEmvLoadAid(TermAid, iHxTermAidNum);
}

/*
 * Class:     com_hxsmart_imateinterface_pbocsdk_PbocApi
 * Method:    iHxEmvLoadCaPublicKey
 * Signature: ([Lcom/hxsmart/imateinterface/pbocsdk/HxCaPublicKey;)I
 */
JNIEXPORT jint JNICALL Java_com_hxsmart_imateinterface_pbocsdk_PbocApi_iHxEmvLoadCaPublicKey
  (JNIEnv *env, jobject thiz, jobjectArray caPublicKeys)
{
	sg_env = env;
	sg_this = thiz;

	if(caPublicKeys == NULL)
		return HXEMV_PARA;

	int iHxCaPublicKeyNum = (*env)->GetArrayLength(env, caPublicKeys);
	int i;
	char szBuffer[500];

	if (iHxCaPublicKeyNum == 0)
		return HXEMV_PARA;

	stHxCaPublicKey CaPublicKey[iHxCaPublicKeyNum];
	memset(CaPublicKey, 0, sizeof(stHxCaPublicKey) * iHxCaPublicKeyNum);

	for (i = 0; i< iHxCaPublicKeyNum; i++) {
		jobject obj = (*env)->GetObjectArrayElement(env, caPublicKeys,i);

		CaPublicKey[i].lE = iGetFieldInt(env, obj, "lE");
		CaPublicKey[i].ucIndex = iGetFieldInt(env, obj, "index");

		int len = iGetFieldString(env, obj, "key", szBuffer);
		if (len <= 248 * 2) {
			vTwoOne(szBuffer, len, CaPublicKey[i].sKey);
			CaPublicKey[i].ucKeyLen = len / 2;
		}
		else
			return HXEMV_PARA;
		if (iGetFieldString(env, obj, "rid", szBuffer) == 10)
			vTwoOne(szBuffer, 10, CaPublicKey[i].sKey);
		else
			return HXEMV_PARA;
	}
	return iHxEmvLoadCaPublicKey(CaPublicKey, iHxCaPublicKeyNum);
}

/*
 * Class:     com_hxsmart_imateinterface_pbocsdk_PbocApi
 * Method:    iHxEmvTransInit
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_hxsmart_imateinterface_pbocsdk_PbocApi_iHxEmvTransInit
  (JNIEnv *env, jobject thiz, jint flag)
{
	sg_env = env;
	sg_this = thiz;

	return iHxEmvTransInit(flag);
}

/*
 * Class:     com_hxsmart_imateinterface_pbocsdk_PbocApi
 * Method:    iHxEmvGetSupportedApp
 * Signature: (I[Lcom/hxsmart/imateinterface/pbocsdk/HxAdfInfo;)I
 */
JNIEXPORT jint JNICALL Java_com_hxsmart_imateinterface_pbocsdk_PbocApi_iHxEmvGetSupportedApp
  (JNIEnv *env, jobject thiz, jint ignoreBlock, jobjectArray adfInfos)
{
	sg_env = env;
	sg_this = thiz;

	if (adfInfos == NULL)
		return HXEMV_PARA;
	int iHxAdfNum = (*env)->GetArrayLength(env, adfInfos);
	if (iHxAdfNum == 0)
		return HXEMV_PARA;

	stHxAdfInfo AdfInfos[iHxAdfNum];
	memset(AdfInfos, 0, sizeof(stHxAdfInfo) * iHxAdfNum);

	int iRet = iHxEmvGetSupportedApp(ignoreBlock, AdfInfos, &iHxAdfNum);
	if ((iRet == HXEMV_OK || iRet == HXEMV_AUTO_SELECT) && iHxAdfNum) {
		int i;
		for (i = 0; i < iHxAdfNum; i++) {
			jobject obj = (*env)->GetObjectArrayElement(env, adfInfos,i);
			vSetFieldByteArray(env, obj, "adfNameBytes", AdfInfos[i].sAdfName, AdfInfos[i].ucAdfNameLen);
			char szBuffer[32+1];
			vOneTwo0(AdfInfos[i].sAdfName, AdfInfos[i].ucAdfNameLen, szBuffer);
			vSetFieldString(env, obj, "adfNameString", szBuffer);
			vSetFieldString(env, obj, "label", AdfInfos[i].szLabel);
			vSetFieldInt(env, obj, "priority", AdfInfos[i].iPriority);
			vSetFieldString(env, obj, "language", AdfInfos[i].szLanguage);
			vSetFieldInt(env, obj, "issuerCodeTableIndex", AdfInfos[i].iIssuerCodeTableIndex);
			strcpy(AdfInfos[i].szPreferredName, "hkhjkhjhjh");
			if (strlen(AdfInfos[i].szPreferredName))
				vSetFieldByteArray(env, obj, "preferredName", AdfInfos[i].szPreferredName, strlen(AdfInfos[i].szPreferredName));
		}
	}
	return iRet;
}

/*
 * Class:     com_hxsmart_imateinterface_pbocsdk_PbocApi
 * Method:    iHxEmvAppSelect
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_hxsmart_imateinterface_pbocsdk_PbocApi_iHxEmvAppSelect
  (JNIEnv *env, jobject thiz, jint ignoreBlock, jstring aid)
{
	sg_env = env;
	sg_this = thiz;

	if (aid == NULL)
		return HXEMV_PARA;

    const char *szAid  =  (*env)->GetStringUTFChars(env, aid ,0);//转换成 char *
    if (szAid == NULL)
		return HXEMV_PARA;

	int iAidLen = strlen(szAid) / 2;
    uchar sAid[16];
    vTwoOne(szAid, iAidLen * 2, sAid);

    (*env)->ReleaseStringUTFChars(env, aid, szAid);

	return iHxEmvAppSelect(ignoreBlock, iAidLen, sAid);
}

/*
 * Class:     com_hxsmart_imateinterface_pbocsdk_PbocApi
 * Method:    iHxEmvGetCardNativeData
 * Signature: (ILcom/hxsmart/imateinterface/pbocsdk/HxTlvData;)I
 */
JNIEXPORT jint JNICALL Java_com_hxsmart_imateinterface_pbocsdk_PbocApi_iHxEmvGetCardNativeData
  (JNIEnv *env, jobject thiz, jint tag, jobject outTlvData)
{
	sg_env = env;
	sg_this = thiz;

	if (outTlvData == NULL)
		return HXEMV_PARA;

	uchar sTag[2], ucTmp;
	uint len = 0;

	memset(sTag, 0, sizeof(sTag));
	ucTmp = (tag >> 8) & 0xFF;
	if (ucTmp)
		sTag[len++] = ucTmp;
	ucTmp = tag & 0xFF;
	if (ucTmp)
		sTag[len++] = ucTmp;

	int iBufferSize = 300;
	uchar sOutTlvData[iBufferSize];
	uchar sOutData[iBufferSize];
	int iOutTlvDataLen = iBufferSize;
	int iOutDataLen = iBufferSize;

	memset(sOutTlvData, 0, sizeof(sOutTlvData));
	memset(sOutData, 0, sizeof(sOutData));
	uchar szBuffer[600];

	int iRet = iHxEmvGetCardNativeData(sTag, &iOutTlvDataLen, sOutTlvData, &iOutDataLen, sOutData);
	if (iRet == HXEMV_OK) {
		vSetFieldByteArray(env, outTlvData, "tlvDataBytes", sOutTlvData, iOutTlvDataLen);
		vOneTwo0(sOutTlvData, iOutTlvDataLen, szBuffer);
		vSetFieldString(env, outTlvData, "tlvDataString", szBuffer);

		vSetFieldByteArray(env, outTlvData, "dataBytes", sOutData, iOutDataLen);
		vOneTwo0(sOutData, iOutDataLen, szBuffer);
		vSetFieldString(env, outTlvData, "dataString", szBuffer);

		vSetFieldInt(env, outTlvData, "tag", tag);
	}
	return iRet;
}

/*
 * Class:     com_hxsmart_imateinterface_pbocsdk_PbocApi
 * Method:    iHxEmvGetData
 * Signature: (ILcom/hxsmart/imateinterface/pbocsdk/HxTlvData;)I
 */
JNIEXPORT jint JNICALL Java_com_hxsmart_imateinterface_pbocsdk_PbocApi_iHxEmvGetData
  (JNIEnv *env, jobject thiz, jint tag, jobject outTlvData)
{
	sg_env = env;
	sg_this = thiz;

	if (outTlvData == NULL)
		return HXEMV_PARA;

	uchar sTag[2], ucTmp;
	uint len = 0;

	memset(sTag, 0, sizeof(sTag));
	ucTmp = (tag >> 8) & 0xFF;
	if (ucTmp)
		sTag[len++] = ucTmp;
	ucTmp = tag & 0xFF;
	if (ucTmp)
		sTag[len++] = ucTmp;

	int iBufferSize = 300;
	uchar sOutTlvData[iBufferSize];
	uchar sOutData[iBufferSize];
	int iOutTlvDataLen = iBufferSize;
	int iOutDataLen = iBufferSize;

	memset(sOutTlvData, 0, sizeof(sOutTlvData));
	memset(sOutData, 0, sizeof(sOutData));
	uchar szBuffer[600];

	int iRet = iHxEmvGetData(sTag, &iOutTlvDataLen, sOutTlvData, &iOutDataLen, sOutData);
	//vWriteLogTxt("iHxEmvGetData ret = %d", iRet);

	if (iRet == HXEMV_OK) {
		vSetFieldByteArray(env, outTlvData, "tlvDataBytes", sOutTlvData, iOutTlvDataLen);
		vOneTwo0(sOutTlvData, iOutTlvDataLen, szBuffer);
		vSetFieldString(env, outTlvData, "tlvDataString", szBuffer);

		vSetFieldByteArray(env, outTlvData, "dataBytes", sOutData, iOutDataLen);
		vOneTwo0(sOutData, iOutDataLen, szBuffer);
		vSetFieldString(env, outTlvData, "dataString", szBuffer);

		vSetFieldInt(env, outTlvData, "tag", tag);
	}
	return iRet;
}

/*
 * Class:     com_hxsmart_imateinterface_pbocsdk_PbocApi
 * Method:    iHxEmvGetLogInfo
 * Signature: (ILjava/lang/Integer;)I
 */
JNIEXPORT jint JNICALL Java_com_hxsmart_imateinterface_pbocsdk_PbocApi_iHxEmvGetLogInfo
  (JNIEnv *env, jobject thiz, jint flag, jobject maxRecNum)
{
	sg_env = env;
	sg_this = thiz;

	if (maxRecNum == NULL)
		return HXEMV_PARA;

	int iMaxRecNum = 0;
	int iRet = iHxEmvGetLogInfo(flag, &iMaxRecNum);
	if (iRet == HXEMV_OK)
		vSetIntegerValue(env, maxRecNum, iMaxRecNum);

	return iRet;
}

/*
 * Class:     com_hxsmart_imateinterface_pbocsdk_PbocApi
 * Method:    iHxEmvReadLog
 * Signature: (II[Ljava/lang/[BLjava/lang/Integer;)I
 */
JNIEXPORT jint JNICALL Java_com_hxsmart_imateinterface_pbocsdk_PbocApi_iHxEmvReadLog
  (JNIEnv *env, jobject thiz, jint flag, jint logNo, jbyteArray cardLog, jobject logLen)
{
	sg_env = env;
	sg_this = thiz;

	if (cardLog == NULL || logLen == NULL)
		return HXEMV_PARA;

	int iLogLen =  (*env)->GetArrayLength(env, cardLog);
	if (iLogLen == 0)
		return HXEMV_PARA;

	uchar* sLog = malloc(iLogLen);
	int iRet = iHxEmvReadLog(flag, logNo, &iLogLen, sLog);
	if (iRet == HXEMV_OK) {
		(*env)->SetByteArrayRegion(env, cardLog, 0, iLogLen, sLog);
		vSetIntegerValue(env, logLen, iLogLen);
	}
	free(sLog);
	return iRet;
}

/*
 * Class:     com_hxsmart_imateinterface_pbocsdk_PbocApi
 * Method:    iHxEmvGPO
 * Signature: (Ljava/lang/String;JILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_hxsmart_imateinterface_pbocsdk_PbocApi_iHxEmvGPO
  (JNIEnv *env, jobject thiz, jstring transTime, jlong ttc, jint transType, jstring amount, jint currencyCode)
{
	sg_env = env;
	sg_this = thiz;

	if (transTime == NULL || amount == NULL)
		return HXEMV_PARA;


    const char *szTransTime  =  (*env)->GetStringUTFChars(env, transTime ,0);
    const char *szAmount  =  (*env)->GetStringUTFChars(env, amount ,0);

    int iRet = iHxEmvGPO((uchar*)szTransTime, (unsigned long)ttc, transType, (uchar*)szAmount, (unsigned int)currencyCode);

    if (szTransTime)
        (*env)->ReleaseStringUTFChars(env, transTime, szTransTime);
    if (szAmount)
        (*env)->ReleaseStringUTFChars(env, amount, szAmount);

	return iRet;
}

/*
 * Class:     com_hxsmart_imateinterface_pbocsdk_PbocApi
 * Method:    iHxEmvSetAmount
 * Signature: (Ljava/lang/String)I
 */
JNIEXPORT jint JNICALL Java_com_hxsmart_imateinterface_pbocsdk_PbocApi_iHxEmvSetAmount
  (JNIEnv *env, jobject thiz, jstring amount)
{
	sg_env = env;
	sg_this = thiz;

	if (amount == NULL)
		return HXEMV_PARA;

	const char *szAmount  =  (*env)->GetStringUTFChars(env, amount ,0);
	int iRet = iHxEmvSetAmount((uchar*)szAmount);
	(*env)->ReleaseStringUTFChars(env, amount,szAmount);

	return iRet;
}
/*
 * Class:     com_hxsmart_imateinterface_pbocsdk_PbocApi
 * Method:    iHxEmvReadRecord
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_hxsmart_imateinterface_pbocsdk_PbocApi_iHxEmvReadRecord
  (JNIEnv *env, jobject thiz)
{
	sg_env = env;
	sg_this = thiz;

	int iRet = iHxEmvReadRecord();

	return iRet;
}

/*
 * Class:     com_hxsmart_imateinterface_pbocsdk_PbocApi
 * Method:    iHxEmvSetPanFlag
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_hxsmart_imateinterface_pbocsdk_PbocApi_iHxEmvSetPanFlag
  (JNIEnv *env, jobject thiz, jint blackFlag, jint separateFlag)
{
	sg_env = env;
	sg_this = thiz;

	return iHxEmvSetPanFlag(blackFlag, separateFlag);
}

/*
 * Class:     com_hxsmart_imateinterface_pbocsdk_PbocApi
 * Method:    iHxEmvOfflineDataAuth
 * Signature: (Lcom/hxsmart/imateinterface/pbocsdk/HxOfflineAuthData;)I
 */
JNIEXPORT jint JNICALL Java_com_hxsmart_imateinterface_pbocsdk_PbocApi_iHxEmvOfflineDataAuth
  (JNIEnv *env, jobject thiz, jobject offlineAuthData)
{
	sg_env = env;
	sg_this = thiz;

	int iNeedCheckCrlFlag;
	unsigned char sRid[5], ucCaIndex, sCertSerNo[3], szBuff[20];
	int iRet = iHxEmvOfflineDataAuth(&iNeedCheckCrlFlag, sRid, &ucCaIndex, sCertSerNo);
	if (iRet == HXEMV_OK) {
		vSetFieldInt(env, offlineAuthData, "needCheckCrlFlag", iNeedCheckCrlFlag);
		vSetFieldInt(env, offlineAuthData, "caIndex", ucCaIndex);
		vSetFieldByteArray(env, offlineAuthData, "ridBytes", sRid, 5);
		vOneTwo0(sRid, 5, szBuff);
		vSetFieldString(env, offlineAuthData, "ridString", szBuff);
		vSetFieldByteArray(env, offlineAuthData, "certSerNoBytes", sCertSerNo, 3);
		vOneTwo0(sCertSerNo, 3, szBuff);
		vSetFieldString(env, offlineAuthData, "certSerNoString", szBuff);
	}
	return iRet;
}

/*
 * Class:     com_hxsmart_imateinterface_pbocsdk_PbocApi
 * Method:    iHxEmvSetIssuerCertCrl
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_hxsmart_imateinterface_pbocsdk_PbocApi_iHxEmvSetIssuerCertCrl
  (JNIEnv *env, jobject thiz, jint issuerCertCrlFlag)
{
	sg_env = env;
	sg_this = thiz;

	return  iHxEmvSetIssuerCertCrl(issuerCertCrlFlag);
}

/*
 * Class:     com_hxsmart_imateinterface_pbocsdk_PbocApi
 * Method:    iHxEmvProcRistrictions
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_hxsmart_imateinterface_pbocsdk_PbocApi_iHxEmvProcRistrictions
  (JNIEnv *env, jobject thiz)
{
	sg_env = env;
	sg_this = thiz;

	return iHxEmvProcRistrictions();
}

/*
 * Class:     com_hxsmart_imateinterface_pbocsdk_PbocApi
 * Method:    iHxEmvTermRiskManage
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_hxsmart_imateinterface_pbocsdk_PbocApi_iHxEmvTermRiskManage
  (JNIEnv *env, jobject thiz)
{
	sg_env = env;
	sg_this = thiz;

	return iHxEmvTermRiskManage();
}

/*
 * Class:     com_hxsmart_imateinterface_pbocsdk_PbocApi
 * Method:    iHxEmvGetCvmMethod
 * Signature: (Ljava/lang/Integer;Ljava/lang/Boolean;)I
 */
JNIEXPORT jint JNICALL Java_com_hxsmart_imateinterface_pbocsdk_PbocApi_iHxEmvGetCvmMethod
  (JNIEnv *env, jobject thiz, jobject cvm, jobject bypassFlag)
{
	sg_env = env;
	sg_this = thiz;

	vWriteLogTxt("vcm = %d", cvm);
	vWriteLogTxt("bypassFlag = %d", bypassFlag);

	if (cvm == NULL ||  bypassFlag == NULL)
		return HXEMV_PARA;

	int iCvm, iBypassFlag;
	int iRet = iHxEmvGetCvmMethod(&iCvm, &iBypassFlag);
	if (iRet == HXEMV_OK) {
		vSetIntegerValue(env, cvm, iCvm);
		vSetBooleanValue(env, bypassFlag, iBypassFlag);
	}
	return iRet;
}

/*
 * Class:     com_hxsmart_imateinterface_pbocsdk_PbocApi
 * Method:    iHxEmvDoCvmMethod
 * Signature: (I[BLjava/lang/Integer;)I
 */
JNIEXPORT jint JNICALL Java_com_hxsmart_imateinterface_pbocsdk_PbocApi_iHxEmvDoCvmMethod
  (JNIEnv *env, jobject thiz, jint cvmProc, jbyteArray vmData, jobject prompt)
{
	sg_env = env;
	sg_this = thiz;

	if (vmData == NULL)
		return HXEMV_PARA;

	int iCvmProc, iPrompt;
	uchar sCvmData[12+1];

	memset(sCvmData, 0, sizeof(sCvmData));

	int len = (*env)->GetArrayLength(env, vmData);
	if (len > 12)
		return HXEMV_PARA;
	char *vm = (*env)->GetByteArrayElements(env, vmData, 0);
	if (vm) {
		memcpy(sCvmData, vm, len);
		(*env)->ReleaseByteArrayElements(env, vmData, vm, 0);
	}


	int iRet = iHxEmvDoCvmMethod(iCvmProc, sCvmData, &iPrompt);
	if (iRet == HXEMV_OK) {
		vSetIntegerValue(env, prompt, iPrompt);
	}
	return iRet;
}

/*
 * Class:     com_hxsmart_imateinterface_pbocsdk_PbocApi
 * Method:    iHxEmvGetCvmSignFlag
 * Signature: (Ljava/lang/Boolean;)I
 */
JNIEXPORT jint JNICALL Java_com_hxsmart_imateinterface_pbocsdk_PbocApi_iHxEmvGetCvmSignFlag
  (JNIEnv *env, jobject thiz, jobject needSignFlag)
{
	sg_env = env;
	sg_this = thiz;

	int iNeedSignFlag;
	int iRet = iHxEmvGetCvmSignFlag(&iNeedSignFlag);
	if (iRet == HXEMV_OK)
		vSetBooleanValue(env, needSignFlag, iNeedSignFlag);
	return iRet;
}

/*
 * Class:     com_hxsmart_imateinterface_pbocsdk_PbocApi
 * Method:    iHxEmvTermActionAnalysis
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_hxsmart_imateinterface_pbocsdk_PbocApi_iHxEmvTermActionAnalysis
  (JNIEnv *env, jobject thiz)
{
	sg_env = env;
	sg_this = thiz;

	return iHxEmvTermActionAnalysis();
}

/*
 * Class:     com_hxsmart_imateinterface_pbocsdk_PbocApi
 * Method:    iHxEmvGac1
 * Signature: (ILjava/lang/Integer;)I
 */
JNIEXPORT jint JNICALL Java_com_hxsmart_imateinterface_pbocsdk_PbocApi_iHxEmvGac1
  (JNIEnv *env, jobject thiz, jint forcedOnline, jobject cardAction)
{
	sg_env = env;
	sg_this = thiz;

	int iCardAction;
	int iRet = iHxEmvGac1(forcedOnline , &iCardAction);
	if (iRet == HXEMV_OK)
		vSetIntegerValue(env, cardAction, iCardAction);

	return iRet;
}

/*
 * Class:     com_hxsmart_imateinterface_pbocsdk_PbocApi
 * Method:    iHxEmvGac2
 * Signature: (Ljava/lang/String;Ljava/lang/String;[BILjava/lang/Integer;)I
 */
JNIEXPORT jint JNICALL Java_com_hxsmart_imateinterface_pbocsdk_PbocApi_iHxEmvGac2
  (JNIEnv *env, jobject thiz, jstring arc, jstring authCode, jbyteArray issuerData, jint issuerDataLen, jobject cardAction)
{
	sg_env = env;
	sg_this = thiz;

	int iCardAction;
	uchar *pszArc = NULL;
	uchar *pszAuthCode = NULL;
	uchar *psIssuerData = NULL;

	const char *value;
	if (arc != NULL) {
		value  =  (*env)->GetStringUTFChars(env, arc ,0);//转换成 char *
		if (value != NULL) {
			pszArc = malloc(strlen(value));
			strcpy(pszArc, value);
			(*env)->ReleaseStringUTFChars(env, arc,value); //释放引用
		}
	}
	if (authCode != NULL) {
		value  =  (*env)->GetStringUTFChars(env, authCode ,0);//转换成 char *
		if (value != NULL) {
			pszAuthCode = malloc(strlen(value));
			strcpy(pszAuthCode, value);
			(*env)->ReleaseStringUTFChars(env, authCode,value); //释放引用
		}
	}
	if (issuerData != NULL) {
		int len = (*env)->GetArrayLength(env, issuerData);
		if (len > issuerDataLen)
			len = issuerDataLen;

		char *data = (*env)->GetByteArrayElements(env, issuerData, 0);
		if (data != NULL && len > 0) {
			psIssuerData = malloc(len);
			memcpy(psIssuerData, data, len);
			(*env)->ReleaseByteArrayElements(env, issuerData, data, 0);
		}
	}
	//vWriteLogTxt("pszArc = %s", pszArc);
	//vWriteLogTxt("pszArc = %s", pszArc);
	//vWriteLogHex("psIssuerData:", psIssuerData, issuerDataLen);
	int iRet = iHxEmvGac2 (pszArc, pszAuthCode, psIssuerData, issuerDataLen, &iCardAction);
	if (pszArc)
		free(pszArc);
	if (pszAuthCode)
		free(pszAuthCode);
	if (psIssuerData)
		free(psIssuerData);

	if (iRet == HXEMV_OK)
		vSetIntegerValue(env, cardAction, iCardAction);

	return iRet;
}

int syncCommon(uchar *sIn, int iInLen, uchar *sOut, int *piOutLen, int timeout)
{
	int retCode;

	jbyteArray dataIn = (*sg_env)->NewByteArray(sg_env,iInLen);
	(*sg_env)->SetByteArrayRegion(sg_env,dataIn, 0, (jint)iInLen, sIn);

	jbyteArray dataOut = (*sg_env)->NewByteArray(sg_env,2048);

	retCode = 1;
    int ret = (int) (*sg_env)->CallIntMethod(sg_env, sg_this,
    		sendReceiveCallBack, dataIn, iInLen, dataOut, timeout);

    if (ret > 0) {
		uchar *bytes = (*sg_env)->GetByteArrayElements(sg_env, dataOut, 0);
		memcpy(sOut, bytes, ret);
		*piOutLen = ret;
		(*sg_env)->ReleaseByteArrayElements(sg_env, dataOut, (jbyte *) bytes, 0);
		retCode = 0;
    }
	(*sg_env)->DeleteLocalRef(sg_env, dataIn);
	(*sg_env)->DeleteLocalRef(sg_env, dataOut);

	return retCode;
}


/*
 * Local Functions
 */
static void vSetIntegerValue(JNIEnv *env, jobject obj, int value)
{
	jclass objclass = (*env)->FindClass(env, "java/lang/Integer");
	jfieldID fieldId =  (*env)->GetFieldID(env, objclass , "value", "I");
	(*env)->SetIntField(env, obj, fieldId, value);
	(*env)->DeleteLocalRef(env, objclass);
}

static void vSetBooleanValue(JNIEnv *env, jobject obj, int value)
{
	jclass objclass = (*env)->FindClass(env, "java/lang/Boolean");
	jfieldID fieldId =  (*env)->GetFieldID(env, objclass , "value", "Z");
	(*env)->SetIntField(env, obj, fieldId, value);
	(*env)->DeleteLocalRef(env, objclass);
}

static void vSetFieldByteArray(JNIEnv *env, jobject obj, const char *szParamName, jbyteArray buffer, int len)
{
	if (buffer == NULL || len == 0)
		return;

    jclass objclass = (*env)->GetObjectClass(env, obj);
	jfieldID fieldId =  (*env)->GetFieldID(env, objclass , szParamName , "[B"); //获得属性句柄

	jbyteArray bytearray = (*env)->NewByteArray(env,len);
	(*env)->SetByteArrayRegion(env, bytearray, 0, len, buffer);
	(*env)->SetObjectField(env, obj, fieldId, bytearray);

	(*env)->DeleteLocalRef(env, bytearray);
}

static void vSetFieldString(JNIEnv *env, jobject obj, const char *szParamName, const char *szValue)
{
	if (obj == NULL)
		return;

    jclass objclass = (*env)->GetObjectClass(env, obj);
	jfieldID fieldId =  (*env)->GetFieldID(env, objclass , szParamName , "Ljava/lang/String;"); //获得属性句柄
	if (fieldId == NULL)
		return;
	if (szValue == NULL)
		szValue = "";
	jstring valueString =  (*env)->NewStringUTF(env, szValue); //构造一个jstring对象
	(*env)->SetObjectField(env, obj , fieldId , valueString); // 设置该字段的值
	(*env)->DeleteLocalRef(env, valueString);
}

static int iGetFieldString(JNIEnv *env, jobject obj, const char *szParamName, char *szValue)
{
	if (obj == NULL)
		return 0;

    jclass objclass = (*env)->GetObjectClass(env, obj);
	jfieldID fieldId = (*env)->GetFieldID(env, objclass , szParamName , "Ljava/lang/String;"); //获得属性句柄

    jstring valueString = (jstring) (*env)->GetObjectField(env, obj , fieldId);//获得属性值
    if (valueString == NULL) {
    	(*env)->DeleteLocalRef(env, objclass);
    	return 0;
    }

    const char *value  =  (*env)->GetStringUTFChars(env, valueString ,0);//转换成 char *
    if (value != NULL) {
    	strcpy(szValue, value);
    	(*env)->ReleaseStringUTFChars(env, valueString,value); //释放引用
    }
	(*env)->DeleteLocalRef(env, objclass);
    return strlen(szValue);
}

static void vSetFieldInt(JNIEnv *env, jobject obj, const char *szParamName, int iValue)
{
	if (obj == NULL)
		return;
    jclass objclass = (*env)->GetObjectClass(env, obj);
	jfieldID fieldId =  (*env)->GetFieldID(env, objclass , szParamName , "I"); //获得属性句柄
	(*env)->SetIntField(env, obj, fieldId, iValue);
	(*env)->DeleteLocalRef(env, objclass);
}

static jint iGetFieldInt(JNIEnv *env, jobject obj, const char *szParamName)
{
    jclass objclass = (*env)->GetObjectClass(env, obj);
	jfieldID fieldId =  (*env)->GetFieldID(env, objclass , szParamName , "I"); //获得属性句柄

	int ret =  (*env)->GetIntField(env, obj , fieldId);
	(*env)->DeleteLocalRef(env, objclass);
	return ret;
}




