/* DO NOT EDIT THIS FILE - it is machine generated */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <android/log.h>
#include "SyncCommon.h"

/* Header for class com_hxsmart_imateinterface_pbocsdk_PbocApi */
#include "iMateDeviceJni.h"
#include "RemoteFunctions.h"

//static JNIEnv *sg_env;

int SFID_RUDLL_FingerprintOpen(JNIEnv *env)
{
	//sg_env = env;
	syncCommonSetEnv(env);
    return iRcTsFingerprintOpen();
}

void SFID_RUDLL_FingerprintClose(JNIEnv *env)
{
	//sg_env = env;
	syncCommonSetEnv(env);
    vRcTsFingerprintClose();
}

void TSFID_RUDLL_SetOverTime(JNIEnv *env, int _timeout)
{
	//sg_env = env;
	syncCommonSetEnv(env);
    vRcTSFID_RUDLL_SetOverTime(_timeout);
}

int TSFID_RUDLL_GetFinger(JNIEnv *env, char fpflag[3],unsigned char fpminu1[200],unsigned char fpminu2[100])
{
	//sg_env = env;
	syncCommonSetEnv(env);
    return iRcTSFID_RUDLL_GetFinger(fpflag, fpminu1, fpminu2);
}

int TSFID_RUDLL_EnrollFinger(JNIEnv *env, char fpflag[3],int order,unsigned char fpminu1[200],unsigned char fpminu2[100])
{
	//sg_env = env;
	syncCommonSetEnv(env);
    return iRcTSFID_RUDLL_EnrollFinger(fpflag, order, fpminu1, fpminu2);
}

int TSFID_RUDLL_SetDeviceNo(JNIEnv *env, char fpflag[3],unsigned char deviceno[12])
{
	//sg_env = env;
	syncCommonSetEnv(env);
    return iRcTSFID_RUDLL_SetDeviceNo(fpflag, deviceno);
}

int TSFID_RUDLL_GetDeviceNo(JNIEnv *env, char fpflag[3],unsigned char deviceno[12])
{
	//sg_env = env;
	syncCommonSetEnv(env);
    return iRcTSFID_RUDLL_GetDeviceNo(fpflag, deviceno);
}

void TSFID_RUDLL_GetErrorMSG(JNIEnv *env, int errorno,char msgptr[MAXLENGTH_ERRORMSG])
{
	//sg_env = env;
	syncCommonSetEnv(env);
    vRcTSFID_RUDLL_GetErrorMSG(errorno, msgptr);
}

int TSFID_RUDLL_SetDeviceType(JNIEnv *env, char fpflag[3],unsigned char devicetype)
{
	//sg_env = env;
	syncCommonSetEnv(env);
    return iRcTSFID_RUDLL_SetDeviceType(fpflag, devicetype);
}

int TSFID_RUDLL_GetDeviceType(JNIEnv *env, char fpflag[3],unsigned char *devicetype)
{
	//sg_env = env;
	syncCommonSetEnv(env);
    return iRcTSFID_RUDLL_GetDeviceType(fpflag, devicetype);
}

int TSFID_RUDLL_GetDeviceInfo(JNIEnv *env, char fpflag[3], char firmver[10], char deviceinfo[10])
{
	//sg_env = env;
	syncCommonSetEnv(env);
    return iRcTSFID_RUDLL_GetDeviceInfo(fpflag, firmver, deviceinfo);
}

/*
 * Class:     com_hxsmart_imateinterface_imatedevice_iMateDevice
 * Method:    SD_Init
 * Signature: ()I
 */
int iMateDevice_SD_Init(JNIEnv *env)
{
	//sg_env = env;
	syncCommonSetEnv(env);
	return _uiRcSD_Init();
}

/*
 * Class:     com_hxsmart_imateinterface_imatedevice_iMateDevice
 * Method:    SD_DeInit
 * Signature: ()V
 */
void iMateDevice_SD_DeInit(JNIEnv *env)
{
	//sg_env = env;
	syncCommonSetEnv(env);
	_vRcSD_DeInit();
}

/*
 * Class:     com_hxsmart_imateinterface_imatedevice_iMateDevice
 * Method:    SDSCConnectDev
 * Signature: ()I
 */
int iMateDevice_SDSCConnectDev(JNIEnv *env)
{
	//sg_env = env;
	syncCommonSetEnv(env);
	return _uiRcSDSCConnectDev();
}

/*
 * Class:     com_hxsmart_imateinterface_imatedevice_iMateDevice
 * Method:    SDSCDisconnectDev
 * Signature: ()I
 */
int iMateDevice_SDSCDisconnectDev(JNIEnv *env)
{
	//sg_env = env;
	syncCommonSetEnv(env);
	return _uiRcSDSCDisconnectDev();
}

/*
 * Class:     com_hxsmart_imateinterface_imatedevice_iMateDevice
 * Method:    SDSCGetFirmwareVer
 * Signature: ([BLjava/lang/Integer;)I
 */
int iMateDevice_SDSCGetFirmwareVer(JNIEnv *env, uchar* firmwareVer, int* firmwareVerLen)
{
	//sg_env = env;
	syncCommonSetEnv(env);
	if (firmwareVer == NULL || firmwareVerLen == NULL || *firmwareVerLen == 0)
		return -1;

	return _uiRcSDSCGetFirmwareVer(firmwareVer, firmwareVerLen);
}

/*
 * Class:     com_hxsmart_imateinterface_imatedevice_iMateDevice
 * Method:    SDSCResetCard
 * Signature: ([BLjava/lang/Integer;)I
 */
int iMateDevice_SDSCResetCard(JNIEnv *env, uchar* atr, int* atrLen)
{
	//sg_env = env;
	syncCommonSetEnv(env);
	if (atr == NULL || atrLen == NULL || *atrLen == 0)
		return -1;

	uint uiRet = _uiRcSDSCResetCard(atr, atrLen);
	return uiRet;

}

/*
 * Class:     com_hxsmart_imateinterface_imatedevice_iMateDevice
 * Method:    SDSCResetController
 * Signature: (I)I
 */
int iMateDevice_SDSCResetController(JNIEnv *env, int SCPowerMode)
{
	//sg_env = env;
	syncCommonSetEnv(env);
	return _uiRcSDSCResetController(SCPowerMode);
}

/*
 * Class:     com_hxsmart_imateinterface_imatedevice_iMateDevice
 * Method:    SDSCTransmit
 * Signature: ([BII[BLjava/lang/Integer;[Ljava/lang/Byte;)I
 */
int iMateDevice_SDSCTransmit(JNIEnv *env, uchar* command, int commandLen, int timeOutMode, uchar* outData, int* outDataLen, uint* cosState)
{
	//sg_env = env;
	syncCommonSetEnv(env);
	if (outData == NULL || outDataLen == NULL || cosState == NULL || *outDataLen == 0)
		return -1;

	uint uiRet = _uiRcSDSCTransmit(command, commandLen, timeOutMode, outData, outDataLen, cosState);

	vWriteLogTxt("iMateDevice_SDSCTransmit uiRet = %d", uiRet);
	return uiRet;
}

/*
 * Class:     com_hxsmart_imateinterface_imatedevice_iMateDevice
 * Method:    SDSCTransmitEx
 * Signature: ([BII[BLjava/lang/Integer;)I
 */
int iMateDevice_SDSCTransmitEx(JNIEnv *env, uchar* command, int commandLen, int timeOutMode, uchar* outData, int* outDataLen)
{
	//sg_env = env;
	syncCommonSetEnv(env);

	if (outData == NULL || outDataLen == NULL|| *outDataLen == 0)
		return -1;
	uint uiRet = _uiRcSDSCTransmitEx(command, commandLen, timeOutMode, outData, outDataLen);
	return uiRet;
}

/*
 * Class:     com_hxsmart_imateinterface_imatedevice_iMateDevice
 * Method:    SDSCGetSDKVersion
 * Signature: ([BLjava/lang/Integer;)I
 */
int iMateDevice_SDSCGetSDKVersion(JNIEnv *env, uchar* version, int* versionLen)
{
	//sg_env = env;
	syncCommonSetEnv(env);
	if (version == NULL || versionLen == NULL || *versionLen == 0)
		return -1;

	uint uiRet = _uiRcSDSCGetSDKVersion(version, versionLen);
	return uiRet;
}

/*
 * Class:     com_hxsmart_imateinterface_imatedevice_iMateDevice
 * Method:    SDSCGetSCIOType
 * Signature: (Ljava/lang/Integer;)I
 */
int iMateDevice_SDSCGetSCIOType(JNIEnv *env, uint* SCIOType)
{
	//sg_env = env;
	syncCommonSetEnv(env);

	if (SCIOType == NULL)
		return -1;
	uint uiRet = _uiRcSDSCGetSCIOType(SCIOType);
	return uiRet;
}

/*
int syncCommon(uchar *sIn, int iInLen, uchar *sOut, int *piOutLen, int timeout)
{
	int retCode;

	//vSetWriteLog(1);

	jbyteArray dataIn = (*sg_env)->NewByteArray(sg_env,iInLen);
	(*sg_env)->SetByteArrayRegion(sg_env,dataIn, 0, (jint)iInLen, sIn);

	jbyteArray dataOut = (*sg_env)->NewByteArray(sg_env,2048);

	jclass objclass = (*sg_env)->FindClass(sg_env, "com/hxsmart/imateinterface/BluetoothThread");
	jmethodID sendReceiveCallBack = (*sg_env)->GetMethodID(sg_env, objclass, "sendReceive", "([BI[BI)I");

	// 获得THIS对象
	jfieldID fieldId =  (*sg_env)->GetStaticFieldID(sg_env, objclass , "THIS", "Lcom/hxsmart/imateinterface/BluetoothThread;");
	jobject bluetoothObj = (*sg_env)->GetStaticObjectField(sg_env, objclass , fieldId);

	retCode = 1;
	int ret = (int) (*sg_env)->CallIntMethod(sg_env, bluetoothObj, sendReceiveCallBack, dataIn, iInLen, dataOut, timeout);

    if (ret > 0) {
		uchar *bytes = (*sg_env)->GetByteArrayElements(sg_env, dataOut, 0);
		memcpy(sOut, bytes, ret);
		*piOutLen = ret;
		(*sg_env)->ReleaseByteArrayElements(sg_env, dataOut, (jbyte *) bytes, 0);
		retCode = 0;
    }
	(*sg_env)->DeleteLocalRef(sg_env, dataIn);
	(*sg_env)->DeleteLocalRef(sg_env, dataOut);
	(*sg_env)->DeleteLocalRef(sg_env, objclass);
	(*sg_env)->DeleteLocalRef(sg_env, bluetoothObj);

	return retCode;
}
*/
