/* DO NOT EDIT THIS FILE - it is machine generated */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <jni.h>
#include <android/log.h>
/* Header for class com_hxsmart_imateinterface_pbocsdk_PbocApi */

#include "RemoteFunctions.h"

# ifndef uint
# define uint unsigned int
# endif

# ifndef uchar
# define uchar unsigned char
# endif

# ifndef ulong
# define ulong unsigned long
# endif

# ifndef ushort
# define ushort unsigned short
# endif

static JNIEnv *sg_env;
static jobject sg_this;

static jmethodID sendReceiveCallBack;

static void vSetIntegerValue(JNIEnv *env, jobject obj, int value);

/*
 * Class:     com_hxsmart_imateinterface_pbocsdk_PbocApi
 * Method:    iHxEmvInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_hxsmart_imateinterface_imatedevice_iMateDevice_jniInit
  (JNIEnv *env, jobject thiz)
{
	sg_env = env;
	sg_this = thiz;

    jclass thisclass = (*env)->GetObjectClass(env, thiz);
    sendReceiveCallBack = (*env)->GetMethodID(env, thisclass, "sendReceiveCallBack", "([BI[BI)I");
    if (sendReceiveCallBack == 0)
    	return 1;

    return 0;
}

/*
 * Class:     com_hxsmart_imateinterface_imatedevice_iMateDevice
 * Method:    fingerprintOpen
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_hxsmart_imateinterface_imatedevice_iMateDevice_fingerprintOpen
  (JNIEnv *env, jobject thiz)
{
	sg_env = env;
	sg_this = thiz;

	return _uiRcFingerprintOpen();
}

/*
 * Class:     com_hxsmart_imateinterface_imatedevice_iMateDevice
 * Method:    fingerprintClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hxsmart_imateinterface_imatedevice_iMateDevice_fingerprintClose
  (JNIEnv *env, jobject thiz)
{
	sg_env = env;
	sg_this = thiz;

	_vRcFingerprintClose();
}

/*
 * Class:     com_hxsmart_imateinterface_imatedevice_iMateDevice
 * Method:    fingerprintLink
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_hxsmart_imateinterface_imatedevice_iMateDevice_fingerprintLink
  (JNIEnv *env, jobject thiz)
{
	sg_env = env;
	sg_this = thiz;

	return _uiRcFingerprintLink();
}

/*
 * Class:     com_hxsmart_imateinterface_imatedevice_iMateDevice
 * Method:    fingerprintSend
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_com_hxsmart_imateinterface_imatedevice_iMateDevice_fingerprintSend
  (JNIEnv *env, jobject thiz, jbyteArray in, jint inLen)
{
	sg_env = env;
	sg_this = thiz;

	if (in == NULL || inLen == 0)
		return;
	int len = (*env)->GetArrayLength(env, in);
	if (len < inLen)
		return;

	uchar sIn[inLen];
	memset(sIn, 0, sizeof(sIn));

	char *data = (*env)->GetByteArrayElements(env, in, 0);
	if (data) {
		memcpy(sIn, data, inLen);
		(*env)->ReleaseByteArrayElements(env, in, data, 0);
	}
	_vRcFingerprintSend(sIn, inLen);
}

/*
 * Class:     com_hxsmart_imateinterface_imatedevice_iMateDevice
 * Method:    fingerprintRecv
 * Signature: ([BLjava/lang/Integer;I)I
 */
JNIEXPORT jint JNICALL Java_com_hxsmart_imateinterface_imatedevice_iMateDevice_fingerprintRecv
  (JNIEnv *env, jobject thiz, jbyteArray out, jobject outLen, jint timeOutMs)
{
	sg_env = env;
	sg_this = thiz;

	if (outLen == NULL || out == NULL)
		return -1;

	uchar sOut[512];
	uint len = 0;
	uint uiRet = _uiRcFingerprintRecv(sOut, &len, timeOutMs);
	if (uiRet == 0) {
		int paramLen = (*env)->GetArrayLength(env, out);
		if (len > paramLen)
			len = paramLen;
		(*env)->SetByteArrayRegion(env, out, 0, len, sOut);
		vSetIntegerValue(env, outLen, len);
	}
	return uiRet;
}

/*
 * Class:     com_hxsmart_imateinterface_imatedevice_iMateDevice
 * Method:    SD_Init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_hxsmart_imateinterface_imatedevice_iMateDevice_SD_1Init
  (JNIEnv *env, jobject thiz)
{
	sg_env = env;
	sg_this = thiz;

	return _uiRcSD_Init();
}

/*
 * Class:     com_hxsmart_imateinterface_imatedevice_iMateDevice
 * Method:    SD_DeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hxsmart_imateinterface_imatedevice_iMateDevice_SD_1DeInit
  (JNIEnv *env, jobject thiz)
{
	sg_env = env;
	sg_this = thiz;

	_vRcSD_DeInit();
}

/*
 * Class:     com_hxsmart_imateinterface_imatedevice_iMateDevice
 * Method:    SDSCConnectDev
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_hxsmart_imateinterface_imatedevice_iMateDevice_SDSCConnectDev
  (JNIEnv *env, jobject thiz)
{
	sg_env = env;
	sg_this = thiz;

	return _uiRcSDSCConnectDev();
}

/*
 * Class:     com_hxsmart_imateinterface_imatedevice_iMateDevice
 * Method:    SDSCDisconnectDev
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_hxsmart_imateinterface_imatedevice_iMateDevice_SDSCDisconnectDev
  (JNIEnv *env, jobject thiz)
{
	sg_env = env;
	sg_this = thiz;

	return _uiRcSDSCDisconnectDev();
}

/*
 * Class:     com_hxsmart_imateinterface_imatedevice_iMateDevice
 * Method:    SDSCGetFirmwareVer
 * Signature: ([BLjava/lang/Integer;)I
 */
JNIEXPORT jint JNICALL Java_com_hxsmart_imateinterface_imatedevice_iMateDevice_SDSCGetFirmwareVer
  (JNIEnv *env, jobject thiz, jbyteArray firmwareVer, jobject firmwareVerLen)
{
	sg_env = env;
	sg_this = thiz;

	if (firmwareVer == NULL || firmwareVerLen == NULL)
		return -1;

	uchar sFirmwareVer[100];
	uint len = sizeof(sFirmwareVer) - 1;
	uint uiRet = _uiRcSDSCGetFirmwareVer(sFirmwareVer, &len);
	if (uiRet == 0) {
		int paramLen = (*env)->GetArrayLength(env, firmwareVer);
		if (len > paramLen)
			len = paramLen;
		(*env)->SetByteArrayRegion(env, firmwareVer, 0, len, sFirmwareVer);
		vSetIntegerValue(env, firmwareVerLen, len);
	}
	return uiRet;
}

/*
 * Class:     com_hxsmart_imateinterface_imatedevice_iMateDevice
 * Method:    SDSCResetCard
 * Signature: ([BLjava/lang/Integer;)I
 */
JNIEXPORT jint JNICALL Java_com_hxsmart_imateinterface_imatedevice_iMateDevice_SDSCResetCard
  (JNIEnv *env, jobject thiz, jbyteArray atr, jobject atrLen)
{
	sg_env = env;
	sg_this = thiz;

	if (atr == NULL || atrLen == NULL)
		return -1;

	uchar sAtr[100];
	uint len = sizeof(sAtr);
	uint uiRet = _uiRcSDSCResetCard(sAtr, &len);
	if (uiRet == 0) {
		int paramLen = (*env)->GetArrayLength(env, atr);
		if (len > paramLen)
			len = paramLen;
		(*env)->SetByteArrayRegion(env, atr, 0, len, sAtr);
		vSetIntegerValue(env, atrLen, len);
	}
	return uiRet;

}

/*
 * Class:     com_hxsmart_imateinterface_imatedevice_iMateDevice
 * Method:    SDSCResetController
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_hxsmart_imateinterface_imatedevice_iMateDevice_SDSCResetController
  (JNIEnv *env, jobject thiz, jint SCPowerMode)
{
	sg_env = env;
	sg_this = thiz;

	return _uiRcSDSCResetController(SCPowerMode);
}

/*
 * Class:     com_hxsmart_imateinterface_imatedevice_iMateDevice
 * Method:    SDSCTransmit
 * Signature: ([BII[BLjava/lang/Integer;[Ljava/lang/Byte;)I
 */
JNIEXPORT jint JNICALL Java_com_hxsmart_imateinterface_imatedevice_iMateDevice_SDSCTransmit
  (JNIEnv *env, jobject thiz, jbyteArray command, jint commandLen, jint timeOutMode, jbyteArray outData, jobject outDataLen, jobjectArray cosState)
{
	sg_env = env;
	sg_this = thiz;

	if (outData == NULL || outDataLen == NULL || cosState == NULL)
		return -1;

	uchar sCommand[300], sOutData[300], sCosState[2];
	uint uiOutLen, uiState;

	vWriteLogTxt("commandLen = %d", commandLen);

	char *data = (*env)->GetByteArrayElements(env, command, 0);
	if (data) {
		memcpy(sCommand, data, commandLen);
		(*env)->ReleaseByteArrayElements(env, command, data, 0);
	}
	uiOutLen = sizeof(sOutData);
	uint uiRet = _uiRcSDSCTransmit(sCommand, commandLen, timeOutMode, sOutData, &uiOutLen, &uiState);
	if (uiRet == 0) {
		int paramLen = (*env)->GetArrayLength(env, outData);
		if (uiOutLen > paramLen)
			uiOutLen = paramLen;
		(*env)->SetByteArrayRegion(env, outData, 0, uiOutLen, sOutData);
		vSetIntegerValue(env, outDataLen, uiOutLen);
		sCosState[0] = uiState/256;
		sCosState[1] = uiState%256;
		(*env)->SetByteArrayRegion(env, cosState, 0, 2, sCosState);
	}
	return uiRet;
}

/*
 * Class:     com_hxsmart_imateinterface_imatedevice_iMateDevice
 * Method:    SDSCTransmitEx
 * Signature: ([BII[BLjava/lang/Integer;)I
 */
JNIEXPORT jint JNICALL Java_com_hxsmart_imateinterface_imatedevice_iMateDevice_SDSCTransmitEx
(JNIEnv *env, jobject thiz, jbyteArray command, jint commandLen, jint timeOutMode, jbyteArray outData, jobject outDataLen)
{
	sg_env = env;
	sg_this = thiz;

	if (outData == NULL || outDataLen == NULL)
		return -1;
	uchar sCommand[300], sOutData[300], sCosState[2];
	uint uiOutLen, uiState;

	char *data = (*env)->GetByteArrayElements(env, command, 0);
	if (data) {
		memcpy(sCommand, data, commandLen);
		(*env)->ReleaseByteArrayElements(env, command, data, 0);
	}

	uiOutLen = sizeof(sOutData);
	uint uiRet = _uiRcSDSCTransmitEx(sCommand, commandLen, timeOutMode, sOutData, &uiOutLen);
	if (uiRet == 0) {
		int paramLen = (*env)->GetArrayLength(env, outData);
		if (uiOutLen > paramLen)
			uiOutLen = paramLen;
		(*env)->SetByteArrayRegion(env, outData, 0, uiOutLen, sOutData);
		vSetIntegerValue(env, outDataLen, uiOutLen);
	}
	return uiRet;
}

/*
 * Class:     com_hxsmart_imateinterface_imatedevice_iMateDevice
 * Method:    SDSCGetSDKVersion
 * Signature: ([BLjava/lang/Integer;)I
 */
JNIEXPORT jint JNICALL Java_com_hxsmart_imateinterface_imatedevice_iMateDevice_SDSCGetSDKVersion
  (JNIEnv *env, jobject thiz, jbyteArray version, jobject versionLen)
{
	sg_env = env;
	sg_this = thiz;

	if (version == NULL || versionLen == NULL)
		return -1;

	uchar sVersion[100];
	uint len = sizeof(sVersion) - 1;
	uint uiRet = _uiRcSDSCGetSDKVersion(sVersion, &len);
	if (uiRet == 0) {
		int paramLen = (*env)->GetArrayLength(env, version);
		if (len > paramLen)
			len = paramLen;
		(*env)->SetByteArrayRegion(env, version, 0, len, sVersion);
		vSetIntegerValue(env, versionLen, len);
	}
	return uiRet;
}

/*
 * Class:     com_hxsmart_imateinterface_imatedevice_iMateDevice
 * Method:    SDSCGetSCIOType
 * Signature: (Ljava/lang/Integer;)I
 */
JNIEXPORT jint JNICALL Java_com_hxsmart_imateinterface_imatedevice_iMateDevice_SDSCGetSCIOType
  (JNIEnv *env, jobject thiz, jobject SCIOType)
{
	sg_env = env;
	sg_this = thiz;

	if (SCIOType == NULL)
		return -1;

	uint uiSCIOType;
	uint uiRet = _uiRcSDSCGetSCIOType(&uiSCIOType);
	if (uiRet == 0)
		vSetIntegerValue(env, SCIOType, uiSCIOType);
	return uiRet;
}

int syncCommon(uchar *sIn, int iInLen, uchar *sOut, int *piOutLen, int timeout)
{
	int retCode;

	jbyteArray dataIn = (*sg_env)->NewByteArray(sg_env,iInLen);
	(*sg_env)->SetByteArrayRegion(sg_env,dataIn, 0, (jint)iInLen, sIn);

	jbyteArray dataOut = (*sg_env)->NewByteArray(sg_env,2048);

	retCode = 1;
    int ret = (int) (*sg_env)->CallIntMethod(sg_env, sg_this,
    		sendReceiveCallBack, dataIn, iInLen, dataOut, timeout);

    if (ret > 0) {
		uchar *bytes = (*sg_env)->GetByteArrayElements(sg_env, dataOut, 0);
		memcpy(sOut, bytes, ret);
		*piOutLen = ret;
		(*sg_env)->ReleaseByteArrayElements(sg_env, dataOut, (jbyte *) bytes, 0);
		retCode = 0;
    }
	(*sg_env)->DeleteLocalRef(sg_env, dataIn);
	(*sg_env)->DeleteLocalRef(sg_env, dataOut);

	return retCode;
}

static void vSetIntegerValue(JNIEnv *env, jobject obj, int value)
{
	jclass objclass = (*env)->FindClass(env, "java/lang/Integer");
	jfieldID fieldId =  (*env)->GetFieldID(env, objclass , "value", "I");
	(*env)->SetIntField(env, obj, fieldId, value);
	(*env)->DeleteLocalRef(env, objclass);
}
